// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDstz5GWGMY32_NJS3SRln59XksVFFP-aE',
    appId: '1:158070960150:web:e52d25644ce6cca4c68537',
    messagingSenderId: '158070960150',
    projectId: 'whatssup-ee360',
    authDomain: 'whatssup-ee360.firebaseapp.com',
    storageBucket: 'whatssup-ee360.appspot.com',
    measurementId: 'G-5EL5PZ7BY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2K0JDKiY9rDX1_jPKJ7ln9ywdHDPxggo',
    appId: '1:158070960150:android:3e75d4366ec8705ac68537',
    messagingSenderId: '158070960150',
    projectId: 'whatssup-ee360',
    storageBucket: 'whatssup-ee360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAddvrky5UeJ4kGbOV8MZNPEtiWyoLZhbk',
    appId: '1:158070960150:ios:12070cde219606f2c68537',
    messagingSenderId: '158070960150',
    projectId: 'whatssup-ee360',
    storageBucket: 'whatssup-ee360.appspot.com',
    iosBundleId: 'com.example.applyPagenation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAddvrky5UeJ4kGbOV8MZNPEtiWyoLZhbk',
    appId: '1:158070960150:ios:12070cde219606f2c68537',
    messagingSenderId: '158070960150',
    projectId: 'whatssup-ee360',
    storageBucket: 'whatssup-ee360.appspot.com',
    iosBundleId: 'com.example.applyPagenation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDstz5GWGMY32_NJS3SRln59XksVFFP-aE',
    appId: '1:158070960150:web:b821f5128e82e2e0c68537',
    messagingSenderId: '158070960150',
    projectId: 'whatssup-ee360',
    authDomain: 'whatssup-ee360.firebaseapp.com',
    storageBucket: 'whatssup-ee360.appspot.com',
    measurementId: 'G-N9VR5M4297',
  );
}
